#cloud-config
users:
- name: ubuntu
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: users, admin
  home: /home/ubuntu
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCFlocFptVmDM+2LZKAd7DqwGuyPRCK0YSe6YEkrIFS9lTXi3y+Ims3rymZXJr05Ayy20Gy7oa9K5h1da9Ne7d0qRKhPig3SAoP+4eeqAnZEEVY9lyHM17wr48QQHHkfxXdaVhYfslxwM0ItmDYm1lfUw0TenWQS7BgJ57jKvz85cibaxzGOG/t4o2TqXzBIYv8DPUI9qnrskWgTCm9CH0hXG/9c64rrgMNNxBKsPll6BUhGj4x9pVhB53uWJ8pdNP4sWc379kIgkFbujau687Nm3Yn9q46oHk7kjTR7emc/Y1GqLzdqRuKYoURpEv16GfbrpmclFYG5dTyUNGhMua1 aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
- apache2
- php
- libapache2-mod-php
write_files:
- path: /var/www/html/info.php
  content: |
    <?php $ihrname = "Nikola Bogosavljevic"; ?>
    <html>
    <head>
    <title><?php echo($ihrname) ?></title>
    </head>
    <body>
    IoT üK
    <br />
    <img src="https://nikolabogosavljevicbucket.s3.amazonaws.com/IMG_3135.jpg" />
    </body>
    </html>

  permissions: '0666'

runcmd:
- sudo a2enconf adminer
- sudo systemctl restart apache2

