#cloud-config
users: #Benutzerliste
- name: ubuntu #Benutzername
  sudo: ALL=(ALL) NOPASSWD:ALL #
  groups: users, admin #Gruppen vom benutzer
  home: /home/ubuntu #home verzeichnis
  shell: /bin/bash #shell Verzeichnis
  ssh_authorized_keys: #erlaubten keys
  - ssh-rsa xxxaaabbbcccxxx aws-key
- name: tbz
  sudo: ALL=(ALL) NOPASSWD:ALL #
  groups: users #Gruppen vom benutzer
  home: /home/ubuntu #home verzeichnis
  shell: /bin/bash #shell Verzeichnis
  inactive: true
ssh_pwauth: false #authentifizierung wir nicht gebraucht
hostname: nikola
disable_root: false #root kann niht deaktiviert werden
package_update: true #package aktualisierung ist möglich
packages: #packages
- curl
- wget
